### ISSUE TITLE
hi guy, I have some questions to ask you.

### ISSUE THREAD

**Issue by LienJack** [ljf0113/ljf0113.github.io#1]
好了，大家都是中国人就不说英语了：)
我是看到你掘金文章2018年度总结过来的。
我也是转行做前端，有一些问题不是太方便在公共场合问，所以能否加个微信私聊一下

附带这个是我个人的一些经历
https://juejin.im/post/5c36fe50518825253b5e94f4

希望见到能回复，十分感谢

**Comment by ljf0113** [comment]
@LienJack 可以的说~ljf_gz 是我的微信

**Comment by LienJack** [comment]
十分感谢
